services:
  qticket-coupon-app:
    image: coupon:latest
    container_name: coupon-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:h2:mem:test_db
      - spring.datasource.username=sa
